### ISSUE TITLE
Unable to update app: Failed to generate quickstart-web.xml.

### ISSUE THREAD

**Issue by vedrax-admin** [GoogleCloudPlatform/appengine-maven-plugin#92]
I'm not able to deploy to GAE. I have updated `gcloud` to the latest version using `gcloud components update` but nothing change. I'm running the application with Java 8. I use the version 1.9.64 for the appengine-maven-plugin.

Added dependencies:

Jersey (Bom version 2.25.1)
Objectify (6.0)
Commons-lang3 (3.3.2)
Commons-code (1.4)
Commons-validator (1.5.0)
io.jsonwebtoken jjwt (0.6.0) 

Thanks for your help.

LOG: 

Beginning interaction for module vedrax-api...
0% Created staging directory at: '/var/folders/l4/f43nrtw55jng64z3196_7wqh0000gn/T/appcfg1422353113919700086.tmp'
5% Scanning for jsp files.

Error Details:
2018-07-09 14:42:32.952:INFO::main: Logging initialized @2112ms
2018-07-09 14:42:34.643:INFO:oejs.Server:main: jetty-9.3.18.v20170406
2018-07-09 14:42:37.859:WARN:oeja.ClassInheritanceHandler:qtp1128032093-12: 
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.eclipse.jetty.annotations.ClassInheritanceHandler.addToInheritanceMap(ClassInheritanceHandler.java:72)
	at org.eclipse.jetty.annotations.ClassInheritanceHandler.handle(ClassInheritanceHandler.java:58)
	at org.eclipse.jetty.annotations.AnnotationParser$MyClassVisitor.visit(AnnotationParser.java:476)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:650)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:525)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:978)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
2018-07-09 14:42:40.855:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=3295ms
2018-07-09 14:42:40.855:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.q.QuickStartWebApp@6a2bcfcb{/,file:///private/var/folders/l4/f43nrtw55jng64z3196_7wqh0000gn/T/appcfg1422353113919700086.tmp/,UNAVAILABLE}
java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///private/var/folders/l4/f43nrtw55jng64z3196_7wqh0000gn/T/appcfg1422353113919700086.tmp/WEB-INF/lib/asm-all-repackaged-2.5.0-b32.jar
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:906)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.ArrayIndexOutOfBoundsException: 32800
	at org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:2605)
	at org.objectweb.asm.ClassReader.readModule(ClassReader.java:757)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:661)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:525)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:978)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
2018-07-09 14:42:40.856:INFO:oejs.Server:main: Started @10021ms
2018-07-09 14:42:40.923:INFO:oejsh.ContextHandler:main: Stopped o.e.j.q.QuickStartWebApp@6a2bcfcb{/,file:///private/var/folders/l4/f43nrtw55jng64z3196_7wqh0000gn/T/appcfg1422353113919700086.tmp/,UNAVAILABLE}
...
java.lang.RuntimeException: Failed to generate quickstart-web.xml.
Unable to update app: Failed to generate quickstart-web.xml.

**Comment by vedrax-admin** [comment]
My dependencies was not up to date
